apiVersion: apps/v1
kind: Deployment
metadata:
  name: cddproj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cddproj
  template:
    metadata:
      labels:
        app: cddproj
    spec:
      containers:
      - name: cddproj
        image: docky9/cddproj:latest
        ports:
        - containerPort: 80
