---
- hosts: kubernetes
  user: ubuntu
  become: yes
  tasks:
    - name: Update Deployment Image
      replace:
        path: /opt/k8s/deployment.yaml
        regexp: 'image: docky9/cddproj:.*'
        replace: 'image: docky9/cddproj:v1.{{ build_id }}'

    - name: Apply Kubernetes Deployment
      command: kubectl apply -f /opt/k8s/deployment.yaml
